### ISSUE TITLE
[FR] numeric keypad markup for command parameters

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [jneilliii/OctoPrint-TerminalCommandsExtended#13]
1. command parameters are a great feature

![image](https://user-images.githubusercontent.com/1622151/85210581-ba009f00-b306-11ea-9551-544e7339631a.png)

2. however, on android, in TouchUI, when editing parameters, say `SIZE_X`
![image](https://user-images.githubusercontent.com/1622151/85210614-0fd54700-b307-11ea-9027-9b77dbe290f6.png)

chrome opens "regular keyboard" 
![image](https://user-images.githubusercontent.com/1622151/85210738-292ac300-b308-11ea-81a5-0538908c46f2.png)

instead of "numeric keypad"
![image](https://user-images.githubusercontent.com/1622151/85210761-4d869f80-b308-11ea-9147-5d85c4e62049.png)

3. at the same time, on the default "control page", for editing "Feed Rate"
chrome opens "numeric keypad"

4. so apparently some `css` markup is required 
to make command parameters use "numeric keypad" by default

**Comment by jneilliii** [comment]
The problem with this is that not all parameters are numeric, so it is acting as desired. Users may want to send an M117 message for example, which is text based.

**Comment by Andrei-Pozolotin** [comment]
ok, can we then have a check box with meaning: "treat this parameter as numeric"?

**Comment by jneilliii** [comment]
I might be able to simplify it a bit and just detect if the default value is numeric and apply the special class that way.

**Comment by Andrei-Pozolotin** [comment]
sounds great, thank you

**Comment by jneilliii** [comment]
feedrate is a slider in the default interface, what is it converted to in TouchUI?

**Comment by jneilliii** [comment]
nevermind, I figure it out. Looks like it's converted to a "number" input type.

**Comment by jneilliii** [comment]
Releasing new version with this change.

**Comment by Andrei-Pozolotin** [comment]
0.1.5 works as expected on android. thank you
