### ISSUE TITLE
Easier icon select?

### ISSUE THREAD

**Issue by BerndJM** [jneilliii/OctoPrint-TerminalCommandsExtended#2]
First at all: a very nice plugin!

Just a suggestion (maybe for a next release?): 
It would be handy to have a search field on the icons select as it is e.g. in the 
TabOrder-Plugin
![Auswahl_099](https://user-images.githubusercontent.com/1837889/74071238-a150b600-4a03-11ea-8cd1-e95288a2421e.png)
This would make the icon select much easier...

**Comment by jneilliii** [comment]
Yeah, there were some technical glitches with the implementation in this plugin that I haven't been able to figure out yet. Will definitely keep trying.

**Comment by jneilliii** [comment]
Just released version 0.1.3 that resolves this by moving the icon selector to the editor window in lieu of the drop-down arrow button option.
