### ISSUE TITLE
Parameters

### ISSUE THREAD

**Issue by tonnic** [jneilliii/OctoPrint-TerminalCommandsExtended#26]
How do I use the parameters?   I tried using %(parameter) and %(parameter)s and it didn't work.

![image](https://user-images.githubusercontent.com/3398173/121289055-9c26a400-c8a1-11eb-805c-5946f25ae7e5.png)

**Comment by jneilliii** [comment]
If you use the little plus sign next to the row of the command parameter it will add the parameter in the correct format. It is case sensitive. In your case it's missing the little s after the last parenthesis, and the parameter `B` is lower case in the command area. 

![image](https://user-images.githubusercontent.com/5249455/121293482-af456e00-c8b9-11eb-85f9-f767ae5ee226.png)
