### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by venucleo** [jneilliii/OctoPrint-TerminalCommandsExtended#28]
Could you implement a choice where to put the button? Like Terminal, Control, Gcode viewer, Temperature.

**Comment by jneilliii** [comment]
I think there are other plugins that allow for adding buttons on other tabs. I personally use my Consolidated Tabs plugin and merge all my tabs into a single page interface.

![image](https://user-images.githubusercontent.com/5249455/126536084-52d86971-9236-4c35-8202-894dc5e75ad0.png)
