### ISSUE TITLE
Is it possible to send non-printable character (ctrl-x) to terminal?

### ISSUE THREAD

**Issue by ImagineerNL** [jneilliii/OctoPrint-TerminalCommandsExtended#29]
The SOFT-RESET function for GRBL language is the only function based on an unprintable character, ctrl-x

Since direct interaction with the terminal doesnt work i was hoping if it is possible to send with the extended commands.
Any way to enable sending of ctrl-x, dec(24) hex(0x18) char(CAN) would be appreciated.

**Comment by jneilliii** [comment]
The plugin just sends what is possible to send to the printer via gcode. I don't think the underlying OctoPrint programming would allow for sending those commands, so I doubt I'd be able to send them, but I'll ask on the Discord to verify.

**Comment by jneilliii** [comment]
I noticed the https://plugins.octoprint.org/plugins/bettergrblsupport/ has reset command defined in it's plugin for the M999 command. So it you had that plugin installed you could use M999.

**Comment by jneilliii** [comment]
For additional information, it appears that the plugin redefines that command to `\x18` so it might be possible to use that for a button as well, I just don't know if it would work.

**Comment by ImagineerNL** [comment]
I have that plugin and totally missed that functionality , will try that, thanks

**Comment by ImagineerNL** [comment]
M999 Works like a charm
