### ISSUE TITLE
The move button seems not to be working.

### ISSUE THREAD

**Issue by leoheck** [jneilliii/OctoPrint-TerminalCommandsExtended#30]
The move button seems not to be working. Am I using it right?

![image](https://user-images.githubusercontent.com/1277920/143880125-42dd4706-510d-4a07-ae94-a8222b7c3a37.png)

I am using this version `0.1.6`

How do I move the `Home-XYZ and FL` button to the first place (top-left)?

**Comment by jneilliii** [comment]
Yeah, I've been meaning to go back and work on the orientation of these, but you should be able to hold down the move button and then drag it into another area in the list.

**Comment by leoheck** [comment]
>  but you should be able to hold down the move button and then drag it into another area in the list.

Well, this is what is not working. Maybe it is browser-related? I am using Chrome

**Comment by leoheck** [comment]
Ah, the same happens on Firefox.

**Comment by jneilliii** [comment]
Can you please share your octoprint.log so I can get a better picture of all the things you have installed? There could potentially be a plugin conflict with another plugin.

**Comment by jneilliii** [comment]
Actually looking back through release notes, this is a bug with current stable version. If you change the plugin's release channel to `Release Candidate` in OctoPrint's Software Update settings and upgrade when prompted the issue should be resolved.

**Comment by leoheck** [comment]
Ah, nice. I will do that.
