### ISSUE TITLE
Update 0.1.6 not possible: File is not a zip file

### ISSUE THREAD

**Issue by FindusD** [jneilliii/OctoPrint-TerminalCommandsExtended#31]
I cannot update to version 0.1.6, the last error message is always "File is not a zip file"

[TerminalCommandExtended0.1.6-Error.txt](https://github.com/jneilliii/OctoPrint-TerminalCommandsExtended/files/8790778/TerminalCommandExtended0.1.6-Error.txt)

**Comment by jneilliii** [comment]
Something is broken here in GitHub's tagging I think. I went ahead and merged the most recent changes that were in RC phase and released version 0.1.7. This update does seem to be working properly.
