### ISSUE TITLE
Feature request: Move command buttons above commands filters

### ISSUE THREAD

**Issue by Luix333** [jneilliii/OctoPrint-TerminalCommandsExtended#34]
First I want to thank the developer for this amazing plugin! This is by far my most used plugin. 
I would like to request the option to move the buttons between the terminal textbox and terminal filters. Would this be possible?

Going from this:
![Screenshot 2022-06-06 202511](https://user-images.githubusercontent.com/27402813/172270771-eb00052f-9cbf-4317-a42a-3cd632441547.png)

To this:
![Untitled](https://user-images.githubusercontent.com/27402813/172270772-869933ed-5fae-4bfd-8a03-bc3367fba08e.png)

**Comment by jneilliii** [comment]
I think I'd be more apt to move those under advanced. You can test by opening your browser's developer tools and in the console tab enter `$('#terminal-filterpanel').prependTo('#term > div:nth-child(3) > div:nth-child(2)');` to get this.

![image](https://user-images.githubusercontent.com/5249455/172283336-26dae563-0b90-4518-a22a-a3466899e36d.png)

![image](https://user-images.githubusercontent.com/5249455/172283377-cd9f1c42-d2e2-4a01-a8ee-ad92a2e3a7a0.png)

**Comment by jneilliii** [comment]
even better...

```
$('#terminal-filterpanel').parent().prependTo('#term > div:nth-child(3) > div:nth-child(2)');
```

![image](https://user-images.githubusercontent.com/5249455/172283738-4f8ba79e-f3c0-470c-9cca-883300b8ffb6.png)

**Comment by Luix333** [comment]
this looks amazing, can you make this part of the plugin?
![image](https://user-images.githubusercontent.com/27402813/172532463-43758aad-ecab-4432-b409-0b1f2a7ed1c2.png)

**Comment by jneilliii** [comment]
Added with the above commit. Go to Software Update section of OctoPrint Software Update settings and change the plugin's release channel to Release Candidate and upgrade when prompted. After enabling the option in the plugin's settings you'll need to refresh your browser.

**Comment by Luix333** [comment]
Thanks!!! <3

**Comment by Luix333** [comment]
Hi, first of all, thanks for this plug-in and you hard work!
Apparently, something on the latest version of octoprint broke this. Can you please look into this at your earliest convenience?
Thanks again for your work and time!

**Comment by jneilliii** [comment]
do you mean in the latest 1.10.0rc2 release?

**Comment by Luix333** [comment]
Sorry, I should have specified. Yes, I'm on 1.10.0rc2 
![image](https://github.com/jneilliii/OctoPrint-TerminalCommandsExtended/assets/27402813/6704a7d6-840a-4769-aa54-3a9e66340bf0)

![image](https://github.com/jneilliii/OctoPrint-TerminalCommandsExtended/assets/27402813/ec7c4cab-fcd6-4530-8323-f6a288a11b95)

**Comment by jneilliii** [comment]
updated in above commit and released as version 0.1.8rc2.

**Comment by Luix333** [comment]
Hi, thank you again for fixing it last time. I'm sorry to inform that the latest release of octoprint (1.10.0) broke it again. Please take a look at it if you can. Thanks again for your time and effort!

**Comment by jneilliii** [comment]
updated in the latest rc version.

**Comment by Luix333** [comment]
Thanks!! 🙏🙏
