### ISSUE TITLE
Send command while printing (Feature request)

### ISSUE THREAD

**Issue by pboucher14** [jneilliii/OctoPrint-TerminalCommandsExtended#4]
Would it be possible to activate a button while a print is in progress?

A setting could be added to specify if a button must be enabled while printing.
I'm asking because sometimes when a spool is almost empty, i  send the command M600
to start a filament change.  I created a button for that command but while i'm printing it is disabled.

**Comment by jneilliii** [comment]
I had that in originally, but didn't think it worked so took it out. I'll add it back and verify it works before posting an updated version.

**Comment by pboucher14** [comment]
Thank you, i will be watching for that.

Patrice Boucher

De : jneilliii<mailto:notifications@github.com>
Envoyé le :10 février 2020 13:36
À : jneilliii/OctoPrint-TerminalCommandsExtended<mailto:OctoPrint-TerminalCommandsExtended@noreply.github.com>
Cc : Patrice Boucher<mailto:patrice_boucher@msn.com>; Author<mailto:author@noreply.github.com>
Objet :Re: [jneilliii/OctoPrint-TerminalCommandsExtended] Send command while printing (Feature request) (#4)


I had that in originally, but didn't think it worked so took it out. I'll add it back and verify it works before posting an updated version.

**Comment by jneilliii** [comment]
Just pushed an update.  You may have to force check in Software Update in settings.

![image](https://user-images.githubusercontent.com/5249455/74206844-1cf07400-4c4b-11ea-8e88-8687a4ae6fb7.png)

**Comment by pboucher14** [comment]
Thank you very much.
I tried it and it works perfectly
