### ISSUE TITLE
Suggestion: Option to add buttons to Control Window instead of Terminal

### ISSUE THREAD

**Issue by MJHirsch1** [jneilliii/OctoPrint-TerminalCommandsExtended#8]
Is it possible to give an option to add the buttons to the Control Window rather than the Terminal Window?   
I only use the Terminal window when dialing in my printer, so having a set of quick commands in the Control would be much more efficient for me.

**Comment by jneilliii** [comment]
That's what [Custom Control Editor](https://plugins.octoprint.org/plugins/customControl/) is for.
